name: pipeline

on:
  push:
    branches: 
    - main

  workflow_dispatch:
    
jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn clean verify

  build:
    name: Build Package
    runs-on: ubuntu-18.04
    needs: run_test

    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Build
        uses: mvn clean package -Dmaven.test.skip=true
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/CICD:latest
  deployment:
      name: Deploy Container
      runs-on: ubuntu-latest
      needs: builds
      steps:
        - name: Deploy using ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            port: 22
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              docker stop springboot-helloworld:latest
              docker rml tasyacitta/springboot-helloworld:latest
              docker pull tasyacitta/springboot-helloworld:latest
              docker run -d --rm --name springboot-helloworld -p 80:8080 -p 443:8080 tasyacitta/springboot-helloworld:latest
          

  