name: Spring Boot Hello World Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn clean verify
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - run: echo "Starting build package"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tasyacitta/springboot-helloworld:latest
  deployment:
     name: Deploy container using SSH
     runs-on: ubuntu-latest
     needs: build
     steps:
      - run: echo "Starting deploy container"
      - uses: actions/checkout@v3
      - name: Copy environment file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          source: ".dev.env"
          target: /home/${{ secrets.SSH_USERNAME }}
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          script: |
            docker stop springboot-helloworld
            docker rmi tasyacitta/springboot-helloworld:latest
            docker pull tasyacitta/springboot-helloworld:latest
            docker run -d --rm --name springboot-helloworld -p 80:8080--env-file .dev.env --network my_network tasyacitta/springboot-helloworld:latest

          

  